# sll_shift_16_single | sll | op1=0x00000001 op2=0x00000010 | reps=1 | mode=single
MARCH = rv32i_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 4k
STOP_TIME = 1ms

include $(TARGETS_DIR)/picorv32/Makefile.inc
