# mul_zero | mul | op1=0x00000000 op2=0xFFFFFFFF | reps=1000 | mode=static
MARCH = rv32im_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 8k
STOP_TIME = 1ms

include $(TARGETS_DIR)/neorv32/Makefile.inc
