# slt_neg_vs_zero | slt | op1=0xFFFFFFFF op2=0x00000000 | reps=1000 | mode=static
MARCH = rv32i_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 8k
STOP_TIME = 1ms

include $(TARGETS_DIR)/picorv32/Makefile.inc
