# add_alternating_accum | add | op1=0xAAAAAAAA op2=0x55555555 | reps=1000 | mode=accum
MARCH = rv32i_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 8k
STOP_TIME = 1ms

include $(TARGETS_DIR)/picorv32/Makefile.inc
