# xor_zeros_single | xor | op1=0x00000000 op2=0x00000000 | reps=1 | mode=single
MARCH = rv32i_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 4k
STOP_TIME = 1ms

include $(TARGETS_DIR)/neorv32/Makefile.inc
