# slt_less_single | slt | op1=0x00000001 op2=0x00000002 | reps=1 | mode=single
MARCH = rv32i_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 4k
STOP_TIME = 1ms

include $(TARGETS_DIR)/picorv32/Makefile.inc
