# ror_rot_1 | ror | op1=0x12345678 op2=0x00000001 | reps=1000 | mode=static
MARCH = rv32i_zbb_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 8k
STOP_TIME = 1ms

include $(TARGETS_DIR)/picorv32/Makefile.inc
