# add_random_single | add | op1=0x12345678 op2=0x9ABCDEF0 | reps=1 | mode=single
MARCH = rv32i_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 4k
STOP_TIME = 1ms

include $(TARGETS_DIR)/picorv32/Makefile.inc
