# sub_underflow | sub | op1=0x80000000 op2=0x7FFFFFFF | reps=1000 | mode=static
MARCH = rv32i_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 8k
STOP_TIME = 1ms

include $(TARGETS_DIR)/neorv32/Makefile.inc
