# or_random_accum | or | op1=0x12345678 op2=0x9ABCDEF0 | reps=1000 | mode=accum
MARCH = rv32i_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 8k
STOP_TIME = 1ms

include $(TARGETS_DIR)/neorv32/Makefile.inc
