# and_all_ones | and | op1=0xFFFFFFFF op2=0xFFFFFFFF | reps=1000 | mode=static
MARCH = rv32i_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 8k
STOP_TIME = 1ms

include $(TARGETS_DIR)/picorv32/Makefile.inc
