# sra_positive_shift_31_single | sra | op1=0x7FFFFFFF op2=0x0000001F | reps=1 | mode=single
MARCH = rv32i_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 4k
STOP_TIME = 1ms

include $(TARGETS_DIR)/picorv32/Makefile.inc
