# mul_ones_single | mul | op1=0x00000001 op2=0x00000001 | reps=1 | mode=single
MARCH = rv32im_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 4k
STOP_TIME = 1ms

include $(TARGETS_DIR)/neorv32/Makefile.inc
