# ror_rot_31_single | ror | op1=0x12345678 op2=0x0000001F | reps=1 | mode=single
MARCH = rv32i_zbb_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 4k
STOP_TIME = 1ms

include $(TARGETS_DIR)/neorv32/Makefile.inc
