# div_neg_by_3 | div | op1=0xFFFFFFFF op2=0x00000003 | reps=1000 | mode=static
MARCH = rv32im_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 8k
STOP_TIME = 1ms

include $(TARGETS_DIR)/neorv32/Makefile.inc
