# sra_positive_shift_31_accum | sra | op1=0x7FFFFFFF op2=0x0000001F | reps=1000 | mode=accum
MARCH = rv32i_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 8k
STOP_TIME = 1ms

include $(TARGETS_DIR)/picorv32/Makefile.inc
