# srl_shift_16 | srl | op1=0x80000000 op2=0x00000010 | reps=1000 | mode=static
MARCH = rv32i_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 8k
STOP_TIME = 1ms

include $(TARGETS_DIR)/picorv32/Makefile.inc
