# div_small_single | div | op1=0x0000000F op2=0x00000003 | reps=1 | mode=single
MARCH = rv32im_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 4k
STOP_TIME = 1ms

include $(TARGETS_DIR)/picorv32/Makefile.inc
