# rol_rot_0_accum | rol | op1=0x12345678 op2=0x00000000 | reps=1000 | mode=accum
MARCH = rv32i_zbb_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 8k
STOP_TIME = 1ms

include $(TARGETS_DIR)/picorv32/Makefile.inc
