# mul_medium | mul | op1=0x0000FFFF op2=0x0000FFFF | reps=1000 | mode=static
MARCH = rv32im_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 8k
STOP_TIME = 1ms

include $(TARGETS_DIR)/neorv32/Makefile.inc
