# mul_large_accum | mul | op1=0x7FFFFFFF op2=0x00000002 | reps=1000 | mode=accum
MARCH = rv32im_zicsr_zifencei
TARGETS_DIR ?= ../../targets
ROM_SIZE = 8k
STOP_TIME = 1ms

include $(TARGETS_DIR)/picorv32/Makefile.inc
